default:
  instructors: "[Carrie Wright](https://carriewright11.github.io/) (cwright2 at fredhutch.org), [Ava Hoffman](https://www.avahoffman.com/) (ahoffma2 at fredhutch.org)"
  r_version: "(4.4.1 (called 'Race for Your Life') as of June 14, 2024)"
  r_dl_mac_m1: "https://cloud.r-project.org/bin/macosx/big-sur-arm64/base/R-4.4.1-arm64.pkg"
  r_dl_mac_intel: "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.4.1-x86_64.pkg"
  r_dl_windows: "https://cloud.r-project.org/bin/windows/base/R-4.4.1-win.exe"
  rstudio_dl_mac: "https://download1.rstudio.org/electron/macos/RStudio-2024.04.2-764.dmg"
  rstudio_dl_windows: "https://download1.rstudio.org/electron/windows/RStudio-2024.04.2-764.exe"

